"""'Init'

Revision ID: 3485b813c924
Revises: 10bef37006ad
Create Date: 2024-06-16 21:01:55.706468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3485b813c924'
down_revision: Union[str, None] = '10bef37006ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('firstname', sa.String(length=50), nullable=False))
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_column('contacts', 'fistname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('fistname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('contacts', 'firstname')
    # ### end Alembic commands ###
